name: Bug Report / Feature Request
about: Report a bug or request a new feature
title: '[BUG]' or '[FEATURE]' - short description
labels: bug, feature request
assignees: ''

---

### Describe the bug / feature request

<!-- A clear and concise description of what the bug is or what feature you'd like -->

### Steps to reproduce (for bugs)

1. Go to '...'
2. Click on '...'
3. See error

### Expected behavior

<!-- What you expected to happen -->

### Screenshots or logs

<!-- If applicable, add screenshots or error logs to help explain your problem -->

### Environment

- OS: [e.g. Ubuntu 22.04, Windows 10]
- Python version: [e.g. 3.11]
- COGNIX version: [if applicable]
- Installed via: [pip, source, etc.]

### Additional context

<!-- Add any other context about the problem or feature request here -->
